#define UNP_RESULT_SUCCESS					0x00U
#define UNP_RESULT_TERMINATE				0x01U
#define UNP_RESULT_TRY_AGAIN				0x02U
#define UNP_RESULT_TRY_ANOTHER_INTERFACE	0x03U
#define UNP_RESULT_SELECT_NEXT				0x04U
#define UNP_RESULT_DECLINE					0x05U
#define UNP_RESULT_ONLINE_REQUEST			0x06U
#define UNP_RESULT_OFFLINE_APPROVE			0x07U
#define UNP_RESULT_ODA_FOR_ONLINE_APPROVE	0x08U
#define UNP_RESULT_INTERRUPT_ICC			0x09U
#define UNP_RESULT_INTERRUPT_MAG_STRIPE		0x0AU
#define UNP_RESULT_PERFORM_CDCVM			0x0BU

#define UNP_MESSAGE_NA						0x00U
#define UNP_MESSAGE_TERMINATE				0x01U
#define UNP_MESSAGE_CARD_EXPIRED			0x02U
#define UNP_MESSAGE_EXCEPTION_FILE			0x03U

#define UNP_LIST_BUFFER_SIZE				512

//		9F10 Issuer Application Data
#define UNP_IAD_AAC												0x00U
#define UNP_IAD_TC												0x10U
#define UNP_IAD_ARQC											0x20U
#define UNP_IAD_RFU												0x30U

//		9F27 Cryptogram Information Data
#define UNP_CID_AAC												0x00U
#define UNP_CID_TC												0x40U
#define UNP_CID_ARQC											0x80U
#define UNP_CID_RFU												0xC0U

//		9F66 Terminal Transaction Qualifiers
#define UNP_TTQ_SUPPORT_CONTACTLESS_DEBIT_CREDIT_APPLICATION	0x40U
#define UNP_TTQ_SUPPORT_QUICS									0x20U
#define UNP_TTQ_SUPPORT_CONTACT_DEBIT_CREDIT_APPLICATION		0x10U
#define UNP_TTQ_OFFLINE_TERMINAL								0x08U
#define UNP_TTQ_SUPPORT_ONLINE_PIN								0x04U
#define UNP_TTQ_SUPPORT_SIGNATURE								0x02U
#define UNP_TTQ_SUPPORT_ODA_FOR_ONLINE_AUTHORIZATION			0x01U
#define UNP_TTQ_REQUIRES_ONLINE_CRYPTOGRAMS						0x80U
#define UNP_TTQ_REQUIRES_CVM									0x40U
#define UNP_TTQ_SUPPORTS_FDDA_OF_01_VERSION						0x80U

//		9F6C Card Transaction Qualifiers
#define UNP_CTQ_REQUIRES_ONLINE_PIN																0x80U
#define UNP_CTQ_REQUIRES_SIGNATURE																0x40U
#define UNP_CTQ_IF_ODA_FAILS_AND_TERMINAL_CAN_GO_ONLINE_THEN_REQUEST_ONLINE						0x20U
#define UNP_CTQ_IF_ODA_FAILS_AND_TERMINAL_SUPPORTS_STANDARD_DEBIT_CREDIT_FLOW_THEN_TERMINATE	0x10U
#define UNP_CTQ_IF_APPLICATION_HAS_EXPIRED_THEN_ONLINE_TRANSACTION								0x08U
#define UNP_CTQ_CDCVM_PERFORMED																	0x80U

//		DF61 Card Additional Function Indicator
#define UNP_CAFI_CREDIT_MODE_LOW_VALUE_PAYMENT_SUPPORTED		0x10U
#define UNP_CAFI_ODA_FOR_ONLINE_AUTHORIZATION_SUPPORTED			0x40U

