//
//============================================================================
//****************************************************************************
//**                                                                        **
//**  PROJECT  : EMV L2                                                     **
//**  PRODUCT  : AS320-A                                                    **
//**                                                                        **
//**  FILE     : EMVCONST.H                                                 **
//**  MODULE   : Declaration of related message string.                     **
//**  VERSION  : V1.00                                                      **
//**  DATE     : 2008/11/27                                                 **
//**  EDITOR   : James Hsieh                                                **
//**                                                                        **
//**  Copyright(C) 2002-2008 SymLink Corporation. All rights reserved.      **
//**                                                                        **
//****************************************************************************
//============================================================================
//
//----------------------------------------------------------------------------
#ifndef _EMVCONST_H_
#define _EMVCONST_H_

//----------------------------------------------------------------------------
//      Terminal Related Data Element
//      ICC      Related Data Element
//----------------------------------------------------------------------------
extern const UCHAR TDE_Tags_Table[];
extern const UINT  TDE_Addr_Table[];
extern const UCHAR IDE_Tags_Table[];
extern const UINT  IDE_Addr_Table[];

//----------------------------------------------------------------------------
#endif
