
//	EMV Data Buffer Size
#define EMV_BUFFER_SIZE_SEND		512
#define EMV_BUFFER_SIZE_RECEIVE		2048

//	EMV Function
#define EMV_FUNCTION_NONE			0
#define EMV_FUNCTION_APPLICATION	1
#define EMV_FUNCTION_PCD			2
#define EMV_FUNCTION_TXNSENDAPP		3

//	EMV Application Mode
#define EMV_MODE_NONE				0
#define EMV_MODE_PREVALIDATION		1
#define EMV_MODE_LOOPBACK			2

//	EMV Transaction Send Application Type
#define EMV_TYPE_APPLICATION_A		0
#define EMV_TYPE_APPLICATION_B		1

//	EMV PCD Function Index
#define EMV_PCD_FUNCTION_NONE		0
#define EMV_PCD_FUNCTION_RESET		1
#define EMV_PCD_FUNCTION_POLLING	2
#define EMV_PCD_FUNCTION_WUPA		3
#define EMV_PCD_FUNCTION_RATS		4
#define EMV_PCD_FUNCTION_WUPB		5
#define EMV_PCD_FUNCTION_ATTRIB		6
#define EMV_PCD_FUNCTION_CARRIERON	7
#define EMV_PCD_FUNCTION_CARRIEROFF	8
#define EMV_PCD_FUNCTION_POWEROFF	9

//	EMV Delay (Micro Second)
#define EMV_DELAY_T_RESET			5100
#define EMV_DELAY_T_P				5100
#define EMV_DELAY_T_RETRANSMISSION	3000
#define EMV_DELAY_T_POWEROFF		15000
