
extern UCHAR	PNQ_ANTICOLLISION_Receive(UINT * rcvLen, UCHAR * rcvCLn);
extern void		PNQ_ANTICOLLISION_Send(UCHAR selCL, ULONG rcvTimeout);
extern UCHAR	PNQ_ATTRIB_Receive(UINT * rcvLen, UCHAR * rcvATA);
extern void		PNQ_ATTRIB_Send(UCHAR * cmdATTRIB, ULONG rcvTimeout);
extern UCHAR	PNQ_AUTHENTICATION(UCHAR iptAutType, UCHAR iptAddress, UCHAR * iptUID);
extern UCHAR	PNQ_Check_SPI_PN5180(void);
extern void		PNQ_Clear_IRQ(void);
extern UCHAR	PNQ_DECREMENT(UCHAR iptAddress, UCHAR * iptValue);
extern UCHAR	PNQ_DEP_Receive(UINT * rcvLen, UCHAR * rcvData);
extern void		PNQ_DEP_Send(UCHAR crdType, UINT datLen, UCHAR * datBuffer, ULONG rcvTimeout);
extern UCHAR	PNQ_Get_CLChipSerialNumber(UCHAR * optData);
extern void		PNQ_HLTA_Send(ULONG rcvTimeout);
extern UCHAR	PNQ_HLTB_Receive(UINT * rcvLen, UCHAR * rcvData);
extern void		PNQ_HLTB_Send(UCHAR * iptPUPI, ULONG rcvTimeout);
extern UCHAR	PNQ_INCREMENT(UCHAR iptAddress, UCHAR * iptValue);
extern void		PNQ_Initialize_Reader(void);
extern UCHAR	PNQ_LOADKEY(UCHAR * iptKey);
extern UCHAR	PNQ_LOADKEYandAUTHENTICATION(UCHAR *iptKey, UCHAR iptAutType, UCHAR iptAddress, UCHAR * iptUID);
extern void		PNQ_Load_Protocol_A(void);
extern void		PNQ_Load_Protocol_B(void);
extern void		PNQ_Load_RF_Parameter_TA(void);
extern UCHAR	PNQ_RATS_Receive(UINT * rcvLen, UCHAR * rcvATS);
extern void		PNQ_RATS_Send(UCHAR ratPARAM, ULONG rcvTimeout);
extern UCHAR	PNQ_READ(UCHAR iptAddress, UCHAR * optData);
extern void		PNQ_REQA_Send(ULONG rcvTimeout);
extern UCHAR	PNQ_REQA_Receive(UINT * rcvLen, UCHAR * rcvATQA);
extern UCHAR	PNQ_REQB_Receive(UINT * rcvLen, UCHAR * rcvATQB);
extern void		PNQ_REQB_Send(ULONG rcvTimeout);
extern UCHAR	PNQ_RESTORE(UCHAR iptAddress);
extern UCHAR	PNQ_SELECT_Receive(UINT * rcvLen, UCHAR * rcvSAK);
extern void		PNQ_SELECT_Send(UCHAR selCL, UCHAR * selUID, UCHAR uidBCC, ULONG rcvTimeout);
extern void		PNQ_Set_IRQ(UCHAR * iptData);
extern void		PNQ_Switch_FieldOff(void);
extern void		PNQ_Switch_FieldOn(void);
extern UCHAR	PNQ_TRANSFER(UCHAR iptAddress);
extern UCHAR	PNQ_WRITE(UCHAR iptAddress, UCHAR * iptData);
extern UCHAR	PNQ_WUPA_Receive(UINT * rcvLen, UCHAR * rcvATQA);
extern void		PNQ_WUPA_Send(ULONG rcvTimeout);
extern UCHAR	PNQ_WUPB_Receive(UINT * rcvLen, UCHAR * rcvATQB);
extern void		PNQ_WUPB_Send(ULONG rcvTimeout);

